using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;
using Thry.ThryEditor.Helpers;

namespace Thry.ThryEditor
{
    /// <summary>
    /// Persistent, content-addressed store for the shaders the ShaderOptimizer generates.
    ///
    /// Locked shaders used to be named after the material's GUID and written next to the material, so
    /// two materials that optimize down to byte-identical code could never share one. Unlocking then
    /// deleted the asset outright, which made every re-lock a fresh compile. Here a locked shader is
    /// named and filed under a hash of everything that affects its generated source, so any material
    /// hashing the same reuses it - across materials, and across editor sessions - and unlocking
    /// leaves the asset in place for the next lock.
    /// </summary>
    public static class LockedShaderCache
    {
        public const string CacheRoot = "Assets/_LockedShaderCache";
        public const string LockedShaderPrefix = "Hidden/Locked/";
        const string SidecarName = ".thrylock";

        const string ReadmeName = "README.txt";
        const string ReadmeContents =
@"This folder holds the optimized shader cache generated by the ShaderOptimizer. If you
are using Poiyomi Shaders, this folder is very important!

- Everything in here is generated. Don't hand-edit it, or your changes will be overwritten.
- DO NOT DELETE THIS FOLDER! Deletion of this folder will cause Pink colors on locked materials and will require a re-compiled unlock!
- Each subfolder is named after a shader, and each folder inside that is one unique combination of material settings. Materials with identical settings share a single shader on purpose, which allows improved performance on Lock and Unlock.
- VERSION CONTROL: This folder can be safely ignored via .gitignore.
- To clear this Cache: Thry > ThryEditor > Optimized Shader Cache > Remove Unused.
";

        #region Naming and Paths

        /// <summary>Name of the locked shader for a given original shader name and content hash.</summary>
        public static string GetLockedShaderName(string originalShaderName, string hash)
        {
            return LockedShaderPrefix + originalShaderName + "/" + hash;
        }

        /// <summary>Folder holding one locked shader.</summary>
        public static string GetEntryDirectory(string originalShaderName, string hash)
        {
            return CacheRoot + "/" + SanitizeFolderName(originalShaderName) + "/" + hash;
        }

        /// <summary>Outputs true if the given asset path lives inside the cache.</summary>
        public static bool IsInCache(string assetPath)
        {
            return !string.IsNullOrEmpty(assetPath) && assetPath.Replace('\\', '/').StartsWith(CacheRoot + "/", StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>
        /// Turns a shader name into one path segment. Shader names carry '/' and often a leading '.'
        /// (".poiyomi/Poiyomi Pro"), and Unity ignores folders that start with '.' or end with '~',
        /// so neither can survive into a folder name.
        /// </summary>
        public static string SanitizeFolderName(string shaderName)
        {
            if (string.IsNullOrEmpty(shaderName)) return "Unnamed";

            StringBuilder sb = new StringBuilder(shaderName.Length);
            char[] invalid = Path.GetInvalidFileNameChars();
            foreach (char c in shaderName)
            {
                if (c == '/' || c == '\\') sb.Append('_');
                else if (Array.IndexOf(invalid, c) >= 0) sb.Append('_');
                else sb.Append(c);
            }

            // Unity skips folders starting with '.' and ending with '~'; Windows rejects names that
            // end in '.' or ' '.
            string result = sb.ToString().TrimStart('.').TrimEnd('~', '.', ' ');
            return string.IsNullOrEmpty(result) ? "Unnamed" : result;
        }

        #endregion

        #region Lookup

        /// <summary>
        /// Finds an already-generated locked shader by name. Only sees shaders the AssetDatabase has
        /// imported, so callers still need their own book-keeping for shaders written earlier in the
        /// same StartAssetEditing block.
        /// </summary>
        public static bool TryGetCachedShader(string lockedShaderName, out Shader shader)
        {
            shader = null;

            // Developer mode edits shader and include sources constantly, and the hash cannot see
            // changes inside included files. Never reuse in that case.
            if (Config.Instance.enableDeveloperMode) return false;

            Shader found = Shader.Find(lockedShaderName);
            if (found == null || found.IsBroken()) return false;

            // A cached shader that failed to compile is worse than no cached shader.
            if (ShaderUtil.ShaderHasError(found)) return false;

            shader = found;
            return true;
        }

        #endregion

        #region Sidecar

        /// <summary>Per-entry book-keeping that has to outlive the editor session.</summary>
        public class EntryInfo
        {
            /// <summary>Texture properties the optimizer removed, so unlock can restore them.</summary>
            public List<string> StrippedTextures = new List<string>();

            /// <summary>GUIDs of the materials known to use this entry. Drives the shared-shader tag.</summary>
            public List<string> UserGuids = new List<string>();
        }

        static string GetSidecarPath(string entryDirectory)
        {
            return entryDirectory + "/" + SidecarName;
        }

        /// <summary>Reads an entry's sidecar. Returns null when it is missing or unreadable.</summary>
        public static EntryInfo ReadEntry(string entryDirectory)
        {
            string path = GetSidecarPath(entryDirectory);
            if (!File.Exists(path)) return null;

            try
            {
                EntryInfo info = new EntryInfo();
                foreach (string raw in File.ReadAllLines(path))
                {
                    string line = raw.Trim();
                    if (line.Length == 0) continue;

                    if (line.StartsWith("strip ", StringComparison.Ordinal))
                        info.StrippedTextures.Add(line.Substring(6));
                    else if (line.StartsWith("user ", StringComparison.Ordinal))
                        info.UserGuids.Add(line.Substring(5));
                }
                return info;
            }
            catch (IOException e)
            {
                ThryLogger.LogWarn("Could not read locked shader cache entry " + path + ": " + e.Message);
                return null;
            }
        }

        public static void WriteEntry(string entryDirectory, EntryInfo info)
        {
            if (info == null) return;

            try
            {
                Directory.CreateDirectory(entryDirectory);

                StringBuilder sb = new StringBuilder();
                sb.AppendLine("# Generated by the Thry Shader Optimizer. Safe to delete.");
                foreach (string tex in info.StrippedTextures.Distinct())
                    sb.Append("strip ").AppendLine(tex);
                foreach (string guid in info.UserGuids.Where(g => !string.IsNullOrEmpty(g)).Distinct())
                    sb.Append("user ").AppendLine(guid);

                File.WriteAllText(GetSidecarPath(entryDirectory), sb.ToString());
            }
            catch (IOException e)
            {
                // Losing the sidecar costs a regeneration next time, nothing more.
                ThryLogger.LogWarn("Could not write locked shader cache entry for " + entryDirectory + ": " + e.Message);
            }
        }

        /// <summary>Adds a material to an entry's user list and marks the entry as recently used.</summary>
        public static void RegisterUser(string entryDirectory, string materialGuid)
        {
            EntryInfo info = ReadEntry(entryDirectory) ?? new EntryInfo();
            if (!string.IsNullOrEmpty(materialGuid) && !info.UserGuids.Contains(materialGuid))
                info.UserGuids.Add(materialGuid);
            WriteEntry(entryDirectory, info);
            Touch(entryDirectory);
        }

        /// <summary>Drops a material from an entry's user list. The shader itself is left for the GC.</summary>
        public static void DeregisterUser(string entryDirectory, string materialGuid)
        {
            EntryInfo info = ReadEntry(entryDirectory);
            if (info == null) return;
            if (info.UserGuids.Remove(materialGuid)) WriteEntry(entryDirectory, info);
        }

        /// <summary>Comma-joined GUID list for TAG_ALL_MATERIALS_GUIDS_USING_THIS_LOCKED_SHADER.</summary>
        public static string GetUserTag(string entryDirectory)
        {
            EntryInfo info = ReadEntry(entryDirectory);
            return info == null ? string.Empty : string.Join(",", info.UserGuids.ToArray());
        }

        /// <summary>Bumps the entry's mtime, which is what the GC uses as its least-recently-used clock.</summary>
        public static void Touch(string entryDirectory)
        {
            try
            {
                if (Directory.Exists(entryDirectory))
                    Directory.SetLastWriteTimeUtc(entryDirectory, DateTime.UtcNow);
            }
            catch (IOException)
            {
                // Recency is a heuristic; failing to record it is not worth surfacing.
            }
        }

        public static void EnsureCacheRoot()
        {
            try
            {
                Directory.CreateDirectory(CacheRoot);
                string readme = CacheRoot + "/" + ReadmeName;
                if (!File.Exists(readme)) File.WriteAllText(readme, ReadmeContents);
            }
            catch (IOException e)
            {
                ThryLogger.LogWarn("Could not create the optimized shader cache folder: " + e.Message);
            }
        }

        #endregion

        #region Garbage Collection

        /// <summary>Every cache entry folder, i.e. CacheRoot/&lt;shader&gt;/&lt;hash&gt;.</summary>
        static List<string> GetAllEntryDirectories()
        {
            List<string> entries = new List<string>();
            if (!Directory.Exists(CacheRoot)) return entries;

            foreach (string shaderDir in Directory.GetDirectories(CacheRoot))
            {
                foreach (string entryDir in Directory.GetDirectories(shaderDir))
                {
                    entries.Add(entryDir.Replace('\\', '/'));
                }
            }

            return entries;
        }

        static long GetDirectorySizeBytes(string directory)
        {
            long size = 0;
            try
            {
                foreach (string file in Directory.GetFiles(directory, "*", SearchOption.AllDirectories))
                    size += new FileInfo(file).Length;
            }
            catch (IOException)
            {
                // Treat an unreadable folder as empty rather than aborting the sweep.
            }
            return size;
        }

        /// <summary>
        /// Cache-relative asset paths that some material still points at. Uses the import database's
        /// dependency info rather than loading materials, which matters because a material on a large
        /// shader deserializes thousands of properties.
        /// </summary>
        static HashSet<string> GetReferencedCachePaths()
        {
            HashSet<string> referenced = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            foreach (string guid in AssetDatabase.FindAssets("t:Material"))
            {
                string materialPath = AssetDatabase.GUIDToAssetPath(guid);
                if (string.IsNullOrEmpty(materialPath)) continue;

                foreach (string dependency in AssetDatabase.GetDependencies(materialPath, false))
                {
                    if (IsInCache(dependency)) referenced.Add(dependency.Replace('\\', '/'));
                }
            }

            return referenced;
        }

        /// <summary>
        /// Deletes cache entries no material references. With <paramref name="budgetBytes"/> above zero
        /// it stops as soon as the cache fits the budget, oldest entry first; otherwise it removes every
        /// unreferenced entry. Returns the number of entries deleted.
        /// </summary>
        public static int CollectGarbage(long budgetBytes = 0, ICollection<string> protectedEntries = null)
        {
            List<string> entries = GetAllEntryDirectories();
            if (entries.Count == 0) return 0;

            HashSet<string> referenced = GetReferencedCachePaths();

            // An entry is live if any material references a file inside it. Entries the caller marks as
            // protected are kept regardless: the import database only knows what is saved to disk, so a
            // material locked moments ago still appears to reference its old shader.
            List<string> unreferenced = entries
                .Where(entry => !(protectedEntries != null && protectedEntries.Contains(entry)))
                .Where(entry => !referenced.Any(r => r.StartsWith(entry + "/", StringComparison.OrdinalIgnoreCase)))
                .ToList();

            if (unreferenced.Count == 0) return 0;

            long total = 0;
            if (budgetBytes > 0)
            {
                foreach (string entry in entries) total += GetDirectorySizeBytes(entry);
                if (total <= budgetBytes) return 0;

                // Least recently used goes first.
                unreferenced = unreferenced.OrderBy(e => Directory.GetLastWriteTimeUtc(e)).ToList();
            }

            int deleted = 0;
            foreach (string entry in unreferenced)
            {
                long entrySize = budgetBytes > 0 ? GetDirectorySizeBytes(entry) : 0;

                if (AssetDatabase.DeleteAsset(entry))
                {
                    deleted++;
                    total -= entrySize;
                }
                else
                {
                    ThryLogger.LogWarn("Could not delete unused locked shader cache entry " + entry);
                }

                if (budgetBytes > 0 && total <= budgetBytes) break;
            }

            if (deleted > 0)
            {
                DeleteEmptyShaderFolders();
                ThryLogger.LogDetail("Removed " + deleted + " unused locked shader" + (deleted == 1 ? "" : "s") + " from " + CacheRoot + ".");
            }

            return deleted;
        }

        static void DeleteEmptyShaderFolders()
        {
            if (!Directory.Exists(CacheRoot)) return;

            foreach (string shaderDir in Directory.GetDirectories(CacheRoot))
            {
                if (Directory.GetDirectories(shaderDir).Length == 0 && Directory.GetFiles(shaderDir).Length == 0)
                    AssetDatabase.DeleteAsset(shaderDir.Replace('\\', '/'));
            }
        }

        /// <summary>
        /// Trims the cache when it grows past the configured budget. Called after a lock/unlock batch,
        /// so it must run outside StartAssetEditing.
        /// </summary>
        public static void CollectGarbageIfOverBudget(ICollection<string> protectedEntries = null)
        {
            int budgetMB = Config.Instance.lockedShaderCacheBudgetMB;
            if (budgetMB <= 0) return; // 0 disables trimming entirely

            long budgetBytes = (long)budgetMB * 1024L * 1024L;

            // Cheap pre-check so the common case never pays for the material sweep.
            long total = 0;
            foreach (string entry in GetAllEntryDirectories())
            {
                total += GetDirectorySizeBytes(entry);
                if (total > budgetBytes) break;
            }
            if (total <= budgetBytes) return;

            CollectGarbage(budgetBytes, protectedEntries);
        }

        /// <summary>Total bytes on disk, and how many locked shaders that covers.</summary>
        public static void GetCacheStats(out long sizeBytes, out int entryCount)
        {
            sizeBytes = 0;
            List<string> entries = GetAllEntryDirectories();
            entryCount = entries.Count;
            foreach (string entry in entries)
                sizeBytes += GetDirectorySizeBytes(entry);
        }

        /// <summary>Deletes the whole cache. Locked materials go pink until they are locked again.</summary>
        public static void Clear()
        {
            foreach (string shaderDir in Directory.Exists(CacheRoot) ? Directory.GetDirectories(CacheRoot) : new string[0])
                AssetDatabase.DeleteAsset(shaderDir.Replace('\\', '/'));
        }

        #endregion
    }

    static class LockedShaderCacheMenu
    {
        const string MenuRoot = "Thry/ThryEditor/Optimized Shader Cache/";

        static string DescribeCache()
        {
            long sizeBytes;
            int entryCount;
            LockedShaderCache.GetCacheStats(out sizeBytes, out entryCount);
            return entryCount + " locked shader" + (entryCount == 1 ? "" : "s") + ", "
                + (sizeBytes / (1024f * 1024f)).ToString("0.0") + " MB";
        }

        [MenuItem(MenuRoot + "Remove Unused", priority = 50)]
        static void RemoveUnused()
        {
            if (!EditorUtility.DisplayDialog("Optimized Shader Cache",
                    "Delete locked shaders that no material uses any more?\n\nCurrently " + DescribeCache()
                    + ".\n\nMaterials that are still locked keep their shaders and are unaffected.",
                    "Remove Unused", "Cancel"))
                return;

            int deleted = LockedShaderCache.CollectGarbage();
            EditorUtility.DisplayDialog("Optimized Shader Cache",
                deleted == 0
                    ? "Nothing to remove - every locked shader is still in use."
                    : "Removed " + deleted + " unused locked shader" + (deleted == 1 ? "" : "s") + ".\n\nNow " + DescribeCache() + ".",
                "OK");
        }

        [MenuItem(MenuRoot + "Clear All", priority = 51)]
        static void ClearAll()
        {
            if (!EditorUtility.DisplayDialog("Optimized Shader Cache",
                    "Delete the entire cache (" + DescribeCache() + ")?\n\n"
                    + "Materials that are currently locked will turn pink until you unlock and re-lock them, "
                    + "or re-lock them via Thry > Materials > Lock All. Nothing else is lost - the cache is "
                    + "rebuilt from your materials.",
                    "Clear All", "Cancel"))
                return;

            LockedShaderCache.Clear();
            AssetDatabase.Refresh();
        }
    }
}
